### PR TITLE
Updated async template code

### PR DESCRIPTION
**Pull request by acdha**
Google changed their recommended JavaScript for the async method to insert the new script tag ahead of the first <script> in the document; I updated the template to match.

### CODE REVIEW

**Comment by clintecker** [comment]
Trusting that you're tested this out and it works ;)

**Comment by clintecker** [comment]
Man I cannot figure out how to merge this, I'll try later ;(

**Comment by acdha** [comment]
"Works on my machine" tested - I can do a more exhaustive (Windows VM) test if you'd like first.

**Comment by clintecker** [comment]
OK MERGED. _phew_

**Comment by acdha** [comment]
Note: I just tested this as far back as XP SP2/IE6 and all seems fine. Thanks for the fast response!

**Pull request merged**
